# Generated by Django 5.1.15 on 2026-06-30 17:18

import apps.loyalty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='referral_code',
            field=models.CharField(default=apps.loyalty.models._default_referral_code, max_length=20, unique=True),
        ),
    ]
