# Generated by Django 5.1.15 on 2026-06-23 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=15)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, max_length=10, verbose_name='PAN')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage', max_digits=5)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11)),
                ('id_proof', models.FileField(blank=True, upload_to='vendors/documents/')),
                ('address_proof', models.FileField(blank=True, upload_to='vendors/documents/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='stores/logos/')),
                ('banner', models.ImageField(blank=True, upload_to='stores/banners/')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-total_sales'],
            },
        ),
        migrations.CreateModel(
            name='StorePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_type', models.CharField(choices=[('RETURN', 'Return Policy'), ('SHIPPING', 'Shipping Policy'), ('PRIVACY', 'Privacy Policy'), ('TERMS', 'Terms & Conditions')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='vendors.store')),
            ],
            options={
                'verbose_name_plural': 'Store Policies',
                'unique_together': {('store', 'policy_type')},
            },
        ),
    ]
